
server:
  port: 8082

spring:
  application:
    name: planning
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5443/postgres
    username: postgres
    password:

eureka:
  client:
    registry-fetch-interval-seconds: 10
  serviceUrl:
    defaultZone: http://localhost:8761/eureka
  instance:
    appname: planning
    instance-id: planning:${spring.application.instance-id:${random.value}}
    prefer-ip-address: true